<?php

namespace AppBundle\Repository;

/**
 * antibioplusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class antibioplusRepository extends \Doctrine\ORM\EntityRepository
{
}
