<?php

namespace AppBundle\Repository;

/**
 * antibiotiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class antibiotiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
