<?php

namespace AppBundle\Repository;

/**
 * bacterieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bacterieRepository extends \Doctrine\ORM\EntityRepository
{
}
