<?php

namespace AppBundle\Repository;

/**
 * etudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class etudeRepository extends \Doctrine\ORM\EntityRepository
{
}
